name: Build Town Schedule CreationCode

on:
  push:
    paths:
      - 'src/**'
      - '.github/workflows/build.yml'
      - 'sonar-project.properties'
    branches:
      - '**'
      - '!releases/**'
  pull_request:
    paths:
      - 'src/**'
      - '.github/workflows/build.yml'
    branches:
      - '**'
      - '!releases/**'

jobs:    
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src

    strategy:
      matrix:
        python-version: ['3.11']

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-game-report.txt
        pip install -r test_requirements.txt
  
    - name: Test with pytest
      run: |
        coverage run -m pytest --junitxml=coverage.xml || true
        coverage xml
  
    - name: Generate reports and fix code coverage paths for Sonarcloud
      run: |
        coverage xml -o coverage.xml
        sed -i 's@'$GITHUB_WORKSPACE'@/github/workspace/@g' coverage.xml

    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
